// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKOlwwDoX9V2kD5zCZNR65i3h9H4q3LYw',
    appId: '1:952774949756:web:bc0b71c917bd701fb0c2f9',
    messagingSenderId: '952774949756',
    projectId: 'demoapp-4b320',
    authDomain: 'demoapp-4b320.firebaseapp.com',
    storageBucket: 'demoapp-4b320.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQPxMwtZ9bPAowoA4wIXFvfKW_C8wUAQ',
    appId: '1:952774949756:android:47b7c349d0358cb0b0c2f9',
    messagingSenderId: '952774949756',
    projectId: 'demoapp-4b320',
    storageBucket: 'demoapp-4b320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2g0jAG4F3fEFMKOgU-nl1ajOpIkzpY7g',
    appId: '1:952774949756:ios:4ccf968417d0f2c0b0c2f9',
    messagingSenderId: '952774949756',
    projectId: 'demoapp-4b320',
    storageBucket: 'demoapp-4b320.appspot.com',
    iosBundleId: 'com.example.firebaseconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2g0jAG4F3fEFMKOgU-nl1ajOpIkzpY7g',
    appId: '1:952774949756:ios:4ccf968417d0f2c0b0c2f9',
    messagingSenderId: '952774949756',
    projectId: 'demoapp-4b320',
    storageBucket: 'demoapp-4b320.appspot.com',
    iosBundleId: 'com.example.firebaseconnect',
  );
}
